#!/bin/bash
set -x
dir="$HOME/.praat-dir/plugin_pralign/"
mkdir -pv $dir
rm -rf $dir*
find . -maxdepth 1 ! -name "\." ! -name "install*" ! -name ".git*" \
				   ! -name "temp*" -print0 | xargs -0 -I{} cp -vR "{}" $dir
