#!/bin/bash
set -ex
echo Setting directory
dir="$HOME/.praat-dir/plugin_pralign/"
echo Clearing out directory
rm -rvf "$dir"
echo Creating directory
mkdir -p "$dir" "./bin"
echo Copy binaries
cp -v ./bin_lin/* ./bin/
echo Copy plugin files
find . -maxdepth 1 ! -name "\." ! -name "install*" ! -name ".*" \
! -name "temp*" ! -name "bin_*" -print0 | xargs -P 2 -0 -I{} cp -vR "{}" "$dir"
echo Installing complete
