#!/bin/bash
set -x
dir="$HOME/Library/Preferences/Praat Prefs/plugin_pralign"
mkdir -pv $dir
rm -rf $dir/*
find . -maxdepth 1 | grep -v "git\|install\|^..\?$\|temp" |\
   	xargs -I{} cp -vR "{}" $dir
